export const TYPES={
    ADD_ORDER:"ADD_ORDER",
    REMOVE_ORDER:"REMOVE_ORDER",
    ADD_STORAGE:"ADD_STORAGE",
    CLEAR_ORDERS:"CLEAR_ORDERS",
    ADD_ELEMENT:"ADD_ELEMENT",
    REMOVE_ELEMENT:"REMOVE_ELEMENT"
}